# Generated by Django 2.0.1 on 2018-02-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kader', '0003_fight_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attended', models.ManyToManyField(to='kader.Member')),
                ('fights', models.ManyToManyField(to='kader.Fight')),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attended',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='fights',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
