# Generated by Django 2.0.1 on 2018-02-10 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kader', '0004_auto_20180210_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='fights',
        ),
        migrations.AddField(
            model_name='fight',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kader.Training'),
        ),
    ]
